### ISSUE TITLE
Could not load worker TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by khanh-nguyen** [thlorenz/brace#156]
I'm using `brace@0.11.1` with `webpack@3.6.x`. (The problem occured in both Firefox and Chrome on Mac OS X Sierra.)

This is how I set it up

```
const ace = require('brace');
require('brace/theme/monokai');
require('brace/mode/json');

//...
const editor = ace.edit(elementId);
editor.setTheme('ace/theme/monokai');
editor.session.setMode('ace/mode/json');
```

While theme is loaded correctly, I got the following error when setting mode

```
Could not load worker TypeError: Cannot read property 'split' of undefined
    at AppConfig.exports.moduleUrl (index.js:4113)
    at new WorkerClient (index.js:18003)
    at Mode.createWorker (json.js:300)
    at EditSession.$startWorker (index.js:10226)
    at EditSession.$onChangeMode (index.js:10182)
    at EditSession.<anonymous> (index.js:10163)
    at AppConfig.exports.loadModule (index.js:4151)
    at EditSession.setMode (index.js:10152)
```

Apperantly, `name` [here](https://github.com/thlorenz/brace/blob/master/index.js#L4109) is `undefined`. 

As the result, syntax check is not working in the editor.

**Comment by khanh-nguyen** [comment]
Tracing through the code I found that `require('../worker/json')` in [this line](https://github.com/thlorenz/brace/blob/master/mode/json.js#L300) returned undefined. 

That's strange.

**Comment by omspacecode** [comment]
Faced similar issue, for quick fix to avoid displaying that warning added a try catch block and closed it.

**Comment by sharq88** [comment]
Faced similar issue on a rollup/vue/brace/vue2-ace-editor combo site. Probably doesn't affect many people but in case someone also goes trough the same:  Tried to replace **brace** to **ace** because brace is now over two years old and needed some updates for async/await. The error was due to the mixed use of the two packages which rollup could not handle too well. Once I eliminated all references to brace the issue gone away. Also used this for my editor: 
```
import * as ace from 'ace-builds'; // for rollup to work
ace.config.set('basePath', '/js/vendor/ace'); // for the mods/themes ...etc to load from the public directory of the webserver
```
