### ISSUE TITLE
w3c-blob not working with (br)ace 1.2.3

### ISSUE THREAD

**Issue by prasikumbhare** [thlorenz/brace#64]
w3c-blob isn't working for me on Chome. Had to comment it out. Instead using the standard Blob api works :).. So i think the w3c-blob api should be removed or at least first a check for standard Blob api should be added..

**Comment by AStoker** [comment]
Bump. Any update on this?

**Comment by thlorenz** [comment]
I'm not fully aware what's broken WRT w3c-blob. Could you elaborate a bit more please?
Have you tried upgrading the version of it?

What solution do you propose to replace it while keeping things working in all browsers?
Could you submit a PR with that solution?

**Comment by AStoker** [comment]
Well, my particular problem comes from a bundling operation that fails to find the w3c blob library (probably due to how it's being loaded?). But `Blob` has support in all browsers (http://caniuse.com/#feat=blobbuilder) at this point, and w3c blob hasn't been updated in 4 years (no recent version). The solution would be to just remove w3c-blob as a dependency and rely on the native browser Blob implementation.

**Comment by thlorenz** [comment]
> The solution would be to just remove w3c-blob as a dependency and rely on the native browser Blob implementation

That might work for you but would break some people still running with older browsers.

> w3c blob hasn't been updated in 4 years 

That's cause it is very simple and works and thus needs no updating

If brace is not finding the blob library it could be due to not being properly installed as a dependency?

I'm not sure .. are you using browserify and run `npm install` and such?
It's odd that you're the only ones with this problem and it works for everyone else.

**Comment by AStoker** [comment]
I know my problem is a bit unique due to the module loader I'm using and the build tools (Aurelia and Aurelia CLI). The reason I pinged this question was because it was "related" in the sense that the library seemed unnecessary. If there's a need for w3c blob, I'm not gonna ask for it to be removed :)  

How far back do you need to support?

**Comment by thlorenz** [comment]
> I know my problem is a bit unique due to the module loader I'm using and the build tools (Aurelia and Aurelia CLI)

OK so brace is only made for use with browserify .. if your module loader doesn't play well with how node + npm + browserify works then you should file an issue there.

> How far back do you need to support?

I don't have that data, but would like to not break users on older browsers and would like to not degrade on compatibility.

Please find another solution, i.e. use a module loader that works and/or fork brace and make a custom adaptation just for your _broken_ (sorry) use case ;)

**Comment by AStoker** [comment]
Sure thing. I wasn't trying to claim that this was broken :) Was just bumping the original question to try and figure something out. Thanks for responding.

**Comment by thlorenz** [comment]
Yeah, I understood that .. next time it would help to clarify that you aren't using a lib the way it is intended to be used, i.e. it states clearly in the readme that it is for browserify.
That way I don't have to spend the time teasing out of you what the actual problem is (in this case your custom loader).

Hope you can figure your problem out ... good luck! :)

**Comment by AStoker** [comment]
Sorry to use your time! Not sure if @prasikumbhare ever solved his problem though :)
